### PR TITLE
Track the proposer panel being opened and closed

### PR DESCRIPTION
**Pull request by hmgibson23**
Adds tracking to account for the new incoming proposer open events that are being sent.

### CODE REVIEW

**Comment by hmgibson23** [comment]
\cc @lindseydew @alastairjardine

**Comment by lindseydew** [comment]
Looks good, though I think we might action type in the query object. Let's look at flex tomorrow

**Comment by lindseydew** [comment]
Added processing based on action type composer will send through

**Comment by hmgibson23** [comment]
:+1:

**Pull request merged**
